#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -f ${DIR}/.env ]
then
  source ${DIR}/.env
fi

export DATA=${DATA:-${HOME}/${NAME}/data}
export IMAGE=${IMAGE:-ahdinosaur/ssb-pub}

export PATH=${PATH}:${HOME}/${NAME}/bin

export BYTES_PER_MEGABYTE=$((10**6))
export TOTAL_MEMORY_IN_BYTES=$(free -b | awk '/Mem\:/ { print $2 }')
export MEMORY_LIMIT=$((${TOTAL_MEMORY_IN_BYTES} - $((200 * ${BYTES_PER_MEGABYTE}))))
