#!/bin/bash

set -e
set -o pipefail

source /etc/default/ssb-pub

SSB_OPTS="${SSB_OPTS:-}"

if [ "${SSB_EBT_ENABLED}" == "yes" ]
then
  SSB_OPTS="${SSB_OPTS} -enable-ebt"
fi

/usr/bin/ssb-pub-go ${SSB_OPTS} -hops "${SSB_HOPS:-2}" -lis ":${SSB_PORT:-8008}" -repo /var/lib/ssb-pub ":${SSB_WS_PORT:-8989}" $@
